### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by mrporsev** [kth-iv1201-group5/recruitment#17]
Create a login template
- Input fields user and password
- The login button triggers the DB handler
- Database handler 
# Front end
- [x] User form with username, password, submit button.
- [ ] Validate input.
- [ ] Show sign in error thrown from database.

# REST API
- [x] Send [202 OK](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202)
- [x] Send [406 Not Acceptable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406)

# JDBC
- [x] Fetch user information.
- [x] Validate user information
- [ ] Send some kind of OK information.
- [ ] Send some error message.

**Comment by arifjehoh** [comment]
https://github.com/eugenp/tutorials/blob/67ba006831a56cb0ae53b5c03caef1395a876ce8/spring-security-modules/spring-security-web-mvc-custom/src/main/java/com/baeldung/web/controller/LoginController.java#L33-L41

**Comment by mrporsev** [comment]
Bootstrap theme was chosen: [_Lux_](https://bootswatch.com/lux/)

Link where cdn was acquired: https://www.bootstrapcdn.com/bootswatch/?theme=8

default web page redirection working: localhost/ redirects to localhost/login

**Comment by mrporsev** [comment]
Useful resources (also published on resources work-bench):
### Thymeleaf
* [Thymeleaf Cheat Sheet](https://github.com/engma/thymeleaf-cheat-sheet)
* [Tutorial: Thymeleaf + Spring](https://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.pdf)
### Spring
* [Spring Annotations Cheat Sheet](https://chenweixiang.github.io/docs/Spring_Annotations_cheat_sheet.pdf)
* [If you didn't like the first one](https://www.jrebel.com/blog/spring-annotations-cheat-sheet)
* [Spring Boot Thymeleaf Video Tutorial](https://www.youtube.com/watch?v=nP7O26fFkjI)
