### ISSUE TITLE
Spring Security - Logout handler & button on views

### ISSUE THREAD

**Issue by mrporsev** [kth-iv1201-group5/recruitment#55]
### Spring Security logout handler & logout button on views after authentication
**Summary**
- Implementation of logout handler inside the security configuration file
- Add logout button at the left top of each view after authentication that redirects to the logout route
- Handle logout through the web-controller

**Checklist**

- [x] Logout handler implemented correctly inside config
- [x] Logout button on all views that can be viewed after authentication
- [x] Correct mapping with web-controller

**Comment by arifjehoh** [comment]
@mrporsev The logout button is here in my branch `arifjehoh-feature-52`. Here is the html for logout that you might want to change.

https://github.com/kth-iv1201-group5/recruitment/blob/52ddb8cd5ead5c5ba3dcd9bb650e46e2fff6c8b0/src/main/resources/templates/navbar.html#L30-L35
